name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python ./DjangoReact/manage.py test
    - name: Execute Django Migrations
      run: |
        python ./DjangoReact/manage.py makemigrations
        python ./DjangoReact/manage.py migrate
    # - name: Execute Django Collect Static
    #   run: |
    #     python ./DjangoReact/manage.py collectstatic --noinput
    - name: Execute Django Runserver
      run: |
        python ./DjangoReact/manage.py runserver
